### ISSUE TITLE
Try pass EIP712 hash to a tx on mock contract, and decode it with TS

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-core#24]

**Comment by pscott** [comment]
Example contract: https://goerli.voyager.online/contract/0x05460ddee442f8b0f019bfadb501628779f8201eb18d5f03c451a60d25a2814b

Example tx: https://goerli.voyager.online/tx/0x662ea27ab39cc841579903134bad4d76e679cc7829171c1e16f554186599cb

Code to extract the signature from an array of felts: https://github.com/snapshot-labs/sx-api/commit/c6f043785b92d2f9dc4eefc5e73e10b98bdae4c5

Code to transform the signature to an array of felts: https://github.com/snapshot-labs/sx-ui/commit/602cab6c94d9e166c9c7844b302f93a47ed86f7b#diff-e499ee85a337132942563d5245927f0eaa86d8ab5585291dad48b87a24d59e79

**Comment by pscott** [comment]
Letting @bonustrack close this issue when he feels like it can be closed :)
